on:
  push:
    branches:
      - f36
    tags:
      - tag
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
      options: --privileged=true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install \
            rpmdevtools \
            mock fedpkg \
            wget
      - name: Download Source
        run: |
          spectool -g *.spec
          ./preloaderkun.sh
      - name: Build RPMS
        run: |
          sudo fedpkg --release f36 mockbuild
      - name: Archive generated rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpm-serene-desktop-backgrounds
          path: results_serene-desktop-backgrounds
      
      